export const firebaseApiKey=process.env.NEXT_PUBLIC_FIREBASE_API_KEY
export const firebaseAuthDomain=process.env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
export const firebaseProjectId=process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID
export const firebaseStorageBucket=process.env.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
export const firebaseSenderId=process.env.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
export const firebaseAppId=process.env.NEXT_PUBLIC_FIREBASE_APP_ID
export const firebaseMeasurementId=process.env.NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID